### ISSUE TITLE
Doesn't seem to work (java.io.IOException: EOF)

### ISSUE THREAD

**Issue by birdie-github** [PGSSoft/scrollscreenshot#13] opened 2017-10-20 15:43 UTC
```
$ java -cp scrollscreenshot-latest.jar com.pgssoft.scrollscreenshot.ScrollScreenShot -i 1 --pathsdk /tmp/android-studio
Screenshot 1 of 5
java.io.IOException: EOF
```

Already tried J2SE 8u152 and 7u80. Does this application has preferences in regard to Android version, adb version, JavaSE version, etc.?

Strace shows that it works but something is missing. On the phone itself I've noticed scrolling but just once.

No files are being produced at all.

**Comment by tomekziel** [comment] 2017-10-31 14:51
Hi! It still works for me. 

My Java version on Windows 8.1 x64:
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

Are you able to grab screenshot using Monitor tool from SDK? 

Or maybe you are trying to grab screenshot of app that prevent such action? Try grabbing launcher screen first.

**Comment by birdie-github** [comment] 2017-10-31 15:06
@tomekziel 

> Are you able to grab screenshot using Monitor tool from SDK?

I'm not an Android dev, how that could be done?

> Or maybe you are trying to grab screenshot of app that prevent such action? Try grabbing launcher screen first.

I'm trying to grab Telegram's secret chat. I'll try.

**Comment by tomekziel** [comment] 2017-11-02 08:10
Confirmed, Telegram secret chat has screenshots disabled. If the onboard screenshot feature (typically POWER + VOLUME DOWN key combination) cannot take a picture, also scrollscreenshot won't be able to do it.

Closing ticket now.

**Closed as completed by tomekziel** 2017-11-02 08:10 UTC
